name: Deploy Infrastructure

on:
  push:
    paths:
      - 'terraform/**'
  pull_request:
    paths:
      - 'terraform/**'
    branches:
      - master
      - main
    # paths-ignore:
    #   - 'terraform/atlantis.yaml'
    #   - 'terraform/atlantis/**'

jobs:
  tf_apply:
    name: Deploy 
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@master

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.13.1
        tf_actions_working_dir: 'terraform'
        tf_actions_subcommand: 'init'
        args: '-var="do_token=${{ secrets.DO_TOKEN }}" -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY}}"'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DIGITALOCEAN_TOKEN:  ${{ secrets.DO_TOKEN }}

    - name: Terraform Validate
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.13.1
        tf_actions_working_dir: 'terraform'
        tf_actions_subcommand: 'validate'

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.13.1
        tf_actions_working_dir: 'terraform'
        tf_actions_subcommand: 'apply'
        args: '-var="do_token=${{ secrets.DO_TOKEN }}"'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}} 
        TF_VAR_do_token: ${{ secrets.DIGITALOCEAN_TOKEN }}
        TF_VAR_postgres_password: ${{ secrets.POSTGRES_PASSWORD }}
        TF_VAR_redis_password: ${{ secrets.REDIS_PASSWORD }}
        TF_VAR_secret_key: ${{ secrets.APP_SECRET_KEY }}
        TF_VAR_jwt_secret: ${{ secrets.JWT_SECRET }}
        TF_VAR_spaces_access_key: ${{ secrets.DO_SPACES_ACCESS_KEY }}
        TF_VAR_spaces_secret_key: ${{ secrets.DO_SPACES_SECRET_KEY }}
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DIGITALOCEAN_TOKEN:  ${{ secrets.DIGITALOCEAN_TOKEN }}
